/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zavrsni.osnovnaskola.view;

import com.github.lgooddatepicker.components.DatePickerSettings;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import zavrsni.osnovnaskola.controller.ObradaRazred;
import zavrsni.osnovnaskola.controller.ObradaSkolskaGodina;
import zavrsni.osnovnaskola.controller.ObradaUcenik;
import zavrsni.osnovnaskola.controller.ObradaUcitelj;
import zavrsni.osnovnaskola.model.Razred;
import zavrsni.osnovnaskola.model.SkolskaGodina;
import zavrsni.osnovnaskola.model.Ucenik;
import zavrsni.osnovnaskola.model.Ucitelj;
import zavrsni.osnovnaskola.util.EdunovaException;

/**
 *
 * @author WEB DOG
 */
public class RazredForma extends javax.swing.JFrame {

    private ObradaRazred obrada;
    private ObradaUcenik obradaUcenik;
    private ObradaSkolskaGodina obradaSkolskaGodina;
    /**
     * Creates new form RazredForma
     */
    public RazredForma() {
        initComponents();
        obrada = new ObradaRazred();
        setTitle(Aplikacija.NASLOV_APP + " | IZBORNIK RAZREDA");
        obradaUcenik=new ObradaUcenik();
        obradaSkolskaGodina=new ObradaSkolskaGodina();
        ucitajGodine();
        ucitajRazrede();
        ucitajUcitelje();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstRazredi = new javax.swing.JList<>();
        txtNaziv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbUcitelji = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDodajUcenika = new javax.swing.JButton();
        btnIzbrisiUcenika = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnIzbrisi = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstUceniciURazredu = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstUcenici = new javax.swing.JList<>();
        txtUvjet = new javax.swing.JTextField();
        btnTrazi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbGodina = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstRazredi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRazrediValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstRazredi);

        jLabel1.setText("NAZIV RAZREDA:");

        jLabel4.setText("RAZREDNIK:");

        jLabel5.setText("UČENICI U RAZREDU:");

        jLabel6.setText("UČENICI U ŠKOLI:");

        btnDodajUcenika.setText(">");
        btnDodajUcenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajUcenikaActionPerformed(evt);
            }
        });

        btnIzbrisiUcenika.setText("<");
        btnIzbrisiUcenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiUcenikaActionPerformed(evt);
            }
        });

        btnDodaj.setText("DODAJ");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzbrisi.setText("IZBRIŠI");
        btnIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiActionPerformed(evt);
            }
        });

        btnPromjeni.setText("PROMJENI");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        jLabel2.setText("RAZREDI:");

        lstUceniciURazredu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUceniciURazreduValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstUceniciURazredu);

        jScrollPane5.setViewportView(lstUcenici);

        btnTrazi.setText("TRAŽI");
        btnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziActionPerformed(evt);
            }
        });

        jLabel3.setText("ŠKOLSKA GODINA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPromjeni, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(btnIzbrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(75, 75, 75))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUvjet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTrazi))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnDodajUcenika)
                                            .addComponent(btnIzbrisiUcenika))))
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(0, 72, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbGodina, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(cmbUcitelji, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(15, 15, 15))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnPromjeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnIzbrisi)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbUcitelji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btnDodajUcenika)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzbrisiUcenika))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrazi))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajUcenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajUcenikaActionPerformed
        DefaultListModel<Ucenik> m;
        try {
            m=(DefaultListModel<Ucenik>) lstUceniciURazredu.getModel();
            m.get(0).toString();
        } catch (Exception e) {
            m= new DefaultListModel<>();
            lstUceniciURazredu.setModel(m);
        }
        boolean postoji;
       for(Ucenik u : lstUcenici.getSelectedValuesList()){
           postoji=false;
           for(int i=0;i<m.size();i++){
               if(u.getId().equals(m.get(i).getId())){
                   postoji=true;
                   break;
               }
           }
           if(!postoji){
               
               
               m.addElement(u);
           }
       }
//       
       
       Ucenik ur = new Ucenik();
       obradaUcenik.setEntitet(ur);
       
//        postaviVrijednostiNaUcenik();
       
//        try {
//            obradaUcenikRazred.create();
//            obradaRazred.update();
//        } catch (EdunovaException e) {
//            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
//        }
       
        
//        lstUceniciURazredu.repaint();
    }//GEN-LAST:event_btnDodajUcenikaActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        if (obrada.getEntitet()==null || 
                obrada.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        postaviVrijednostiNaEntitet();

        try {
            obrada.update();
            pocisti();
            ucitajRazrede();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
        
        
        
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void lstRazrediValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRazrediValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        if (lstRazredi.getSelectedValue() == null) {
            return;
        }

        obrada.setEntitet(lstRazredi.getSelectedValue());
        
        var r= obrada.getEntitet();
        
        
        txtNaziv.setText(r.getNaziv());
        
        
        
        DefaultComboBoxModel<Ucitelj> mp = 
                (DefaultComboBoxModel<Ucitelj>) 
                cmbUcitelji.getModel();
        for(int i=0;i<mp.getSize();i++){
            if(mp.getElementAt(i).getId().equals(r.getUcitelj().getId())){
                cmbUcitelji.setSelectedIndex(i);
                break;
            }
        }
        
        DefaultComboBoxModel<SkolskaGodina> np = 
                (DefaultComboBoxModel<SkolskaGodina>) 
                cmbGodina.getModel();
        for(int i=0;i<np.getSize();i++){
            if(np.getElementAt(i).getId().equals(r.getSkolskagodina().getId())){
                cmbGodina.setSelectedIndex(i);
                break;
            }
        }
        
       
      
      
       
        
        
        DefaultListModel<Ucenik> m = new DefaultListModel<>();
        m.addAll(r.getUcenici());
        lstUceniciURazredu.setModel(m);
        
        
    }//GEN-LAST:event_lstRazrediValueChanged

    private void btnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziActionPerformed
        DefaultListModel<Ucenik> m = new DefaultListModel<>();
        m.addAll(obradaUcenik.getPodaci(txtUvjet.getText()));
        lstUcenici.setModel(m);
    }//GEN-LAST:event_btnTraziActionPerformed

    private void btnIzbrisiUcenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiUcenikaActionPerformed
        DefaultListModel<Ucenik> m;
        try {
            m=(DefaultListModel<Ucenik>) lstUceniciURazredu.getModel();
            m.get(0).toString();
        } catch (Exception e) {
           return;
        }
        
        for(Ucenik ur : lstUceniciURazredu.getSelectedValuesList()){
          
           for(int i=0;i<m.size();i++){
               if(ur.getId().equals(m.get(i).getId())){
                   m.removeElementAt(i);
                   break;
               }
           }
          
       }
    }//GEN-LAST:event_btnIzbrisiUcenikaActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        obrada.setEntitet(new Razred());
        postaviVrijednostiNaEntitet();

        try {
            obrada.create();
            pocisti();
            ucitajRazrede(); 
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getPoruka());
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiActionPerformed
        if (obrada.getEntitet()==null || 
                obrada.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }

        try {
            obrada.delete();
            pocisti();
            ucitajRazrede();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnIzbrisiActionPerformed

    private void lstUceniciURazreduValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUceniciURazreduValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        if (lstUceniciURazredu.getSelectedValue() == null) {
            return;
        }
        
        Ucenik u = lstUceniciURazredu.getSelectedValue();
        
         
    }//GEN-LAST:event_lstUceniciURazreduValueChanged

    private void ucitajRazrede() {
        DefaultListModel<Razred> m = new DefaultListModel<>();

        m.addAll(obrada.getPodaci());

        lstRazredi.setModel(m);

    }
     
      private void ucitajUcitelje() {
         
         DefaultComboBoxModel<Ucitelj> m =
                 new DefaultComboBoxModel<>();
         
        m.addAll(new ObradaUcitelj().getPodaci());
        

        cmbUcitelji.setModel(m);
        cmbUcitelji.setSelectedIndex(-1);
        
    }
      
      
      private void ucitajGodine() {
        DefaultComboBoxModel<SkolskaGodina> m = new DefaultComboBoxModel<>();

        m.addAll(new ObradaSkolskaGodina().getPodaci());

        cmbGodina.setModel(m);
        cmbGodina.setSelectedIndex(-1);
        
        

        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajUcenika;
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JButton btnIzbrisiUcenika;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JButton btnTrazi;
    private javax.swing.JComboBox<SkolskaGodina> cmbGodina;
    private javax.swing.JComboBox<Ucitelj> cmbUcitelji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<Razred> lstRazredi;
    private javax.swing.JList<Ucenik> lstUcenici;
    private javax.swing.JList<Ucenik> lstUceniciURazredu;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtUvjet;
    // End of variables declaration//GEN-END:variables

//    
    
    private void postaviVrijednostiNaEntitet() {
       var g = obrada.getEntitet();
       g.setNaziv(txtNaziv.getText());
       g.setUcitelj((Ucitelj) cmbUcitelji.getSelectedItem());
       g.setSkolskagodina((SkolskaGodina) cmbGodina.getSelectedItem());
       
       DefaultListModel<Ucenik> m;
        try {
            m=(DefaultListModel<Ucenik>) lstUceniciURazredu.getModel();
            g.setUcenici(new ArrayList<>());
            for(int i=0;i<m.getSize();i++){
                g.getUcenici().add(m.get(i));
            }
        } catch (Exception e) {
           
        }
        
       
       
    }
    
    
    private void pocisti() {
        txtNaziv.setText("");
        DefaultListModel<Ucenik> m = new DefaultListModel<>();
        cmbUcitelji.setSelectedIndex(-1);
        cmbGodina.setSelectedIndex(-1);
        lstUceniciURazredu.setModel(m);
        
    }

}
